apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: changeme
bases:
  - ../base/
patchesStrategicMerge:
  - deployment.yaml
images:
- name: nginx
  newTag: 1.16.1
nameSuffix: -staging